Added Dockerfile for release/cepp
ExtensionEngine/tailor pull request #1112
Opened 2023-12-12 08:38 UTC by izderic

* Added Dockerfile for release/cepp
* Moved dargs, poi, sequelize-cli and umzug to regular dependencies to fix Module not Found errors

2023-12-12 10:11 UTC, ikovac requested changes

2023-12-12 10:11 UTC, ikovac commented on .dockerignore
> +.env
We can also ignore the dist folder?

2023-12-12 10:11 UTC, ikovac commented on Dockerfile
> +FROM node:14.21.3-slim@sha256:21b6dc452bd2c066724bd5be0f7256ef81a068c47de1adead10a2f810557de02 AS base
Why are we not using bookworm-slim for the runner image?

2023-12-12 10:11 UTC, ikovac commented on Dockerfile
> +FROM node:14.21.3@sha256:2cafa3fbb0b6529ee4726b4f599ec27ee557ea3dea7019182323b3779959927f AS install
We can use bookworm image as install image

2023-12-12 10:11 UTC, ikovac commented on package.json
> +    "poi": "^12.10.3",
Please revert this change and install missing `mississipi` package (required in amazon storage file)

2023-12-12 10:39 UTC, izderic commented on Dockerfile
> +FROM node:14.21.3-slim@sha256:21b6dc452bd2c066724bd5be0f7256ef81a068c47de1adead10a2f810557de02 AS base
I could not find bookworm-slim for this node version.

2023-12-12 10:45 UTC, izderic commented on Dockerfile
> +FROM node:14.21.3@sha256:2cafa3fbb0b6529ee4726b4f599ec27ee557ea3dea7019182323b3779959927f AS install
Looks like bookworm and bookworm-slim are available only in newer versions of node.

2023-12-12 11:00 UTC, ikovac approved these changes

2023-12-13 14:33 UTC, abasic approved these changes

2023-12-13 14:34 UTC, merged