Fix assessment saving #
ExtensionEngine/tailor pull request #589
Opened 2020-08-27 12:35 UTC by zcuric

### This PR
- [x] Closes #588

2020-08-27 14:04 UTC, kjuej commented
@zcuric This creates issues when adding normal assessments as content:

They're automatically saved upon adding, instead of being added in edit mode
When you add an answer they automatically get saved again

2020-09-09 13:48 UTC, underscope requested changes

2020-09-09 13:48 UTC, underscope commented on client/components/common/tce-core/QuestionContainer/index.vue
> +        this.isEditing = !this.element.id;
This flips newly added assessment in the standard container into 'saved' mode (since once BE responds it 'autosaves').

2020-09-09 13:48 UTC, underscope commented on client/components/common/tce-core/QuestionContainer/index.vue
> +        this.editedElement = cloneDeep(this.element);
This overrides the current state upon BE response (which is a problem if there is a delay).

2020-10-08 20:26 UTC, underscope commented
Closing this one until revisited.

2020-10-08 20:26 UTC, closed without merging