Implement publish notification system
ExtensionEngine/tailor pull request #702
Opened 2020-12-11 11:54 UTC by hrvojevu

### Note:
Node version needs to be updated to `12.13.0` (LTS) or higher since the `simple-oauth2` v4 requires Node 12.x or higher (https://github.com/lelylan/simple-oauth2#requirements)

2020-12-18 09:23 UTC, MiroDojkic requested changes
@hrvojevu left a couple of thoughts. Please check if any of them make sense. 🙃

2020-12-18 09:23 UTC, MiroDojkic commented on .env.example
> +CONSUMER_CLIENT_TOKEN_PATH=
Are these used to construct URL to consumer API's token endpoint?
If so, we might be able to simplify configuration a bit by replacing these with a single `CONSUMER_CLIENT_TOKEN_URL` variable.

2020-12-18 09:23 UTC, MiroDojkic commented on server/shared/publishing/oauthClient.js
> +const webhookUrl = config.webhookUrl;
Please consider destructuring these properties to reduce noise.

2020-12-18 09:23 UTC, MiroDojkic commented on server/shared/publishing/oauthClient.js
> +let accessToken = deferred.resolve();
What's the idea behind the deferred?
Maybe I'm missing something, but seems to me that `deferred.resolve()` will resolve promise that's created in Deferred constructor, resulting in undefined value being assigned to `accessToken`.
If that's the case, result of promise from `deferred.promise = getAccessToken()` is never used.

2020-12-18 09:23 UTC, MiroDojkic commented on server/shared/publishing/oauthClient.js
> +'use strict';
Would a name `webhook.js` or `webhookProvider.js` describe more accurately what this module does?

2020-12-18 09:23 UTC, MiroDojkic commented on server/shared/publishing/publishing.service.js
> +      .then(data => oauthClient.send(data) && data));
Sorry for nitpicking, but would this be a bit easier to read if we'd move callback with the promise chain to a variable?
For example
```suggestion
    const publish = () => publishActivity(activity)
      .then(data => oauthClient.send(data) && data);
    return this.queue.add(publish);
```

2020-12-18 09:23 UTC, MiroDojkic commented on server/shared/publishing/oauthClient.js
> +'use strict';
Also, this whole module seems generic, so it might be worth considering to move it out of `publishing` module.

2021-01-19 12:21 UTC, hrvojevu commented on .env.example
> +CONSUMER_CLIENT_TOKEN_PATH=
These variables are used for `simple-oauth2` `ClientCredentials` configuration and this configuration requires `tokenHost` and `tokenPath` to be two properties.

2021-01-21 16:27 UTC, MiroDojkic approved these changes
Left one small suggestion, otherwise seems good to me.

2021-01-21 16:27 UTC, MiroDojkic commented on config/server/consumer.js
> +  clientID: env.CONSUMER_CLIENT_ID,
I believe the convention here would imply camelcase:
```suggestion
  clientId: env.CONSUMER_CLIENT_ID,
```
You wouldn't need to alias it when importing [here](https://github.com/ExtensionEngine/tailor/pull/702/files#diff-7efff118cb81130382f12499a92b5d65874901ddd644818c97a1cfc3596cee5aR4)

2021-01-22 09:46 UTC, merged