Fix repository card tags position issue on lower screen size
ExtensionEngine/tailor pull request #709
Opened 2020-12-16 15:26 UTC by hrvojevu

Per issue: https://github.com/ExtensionEngine/tailor/issues/690

2020-12-16 15:28 UTC, hrvojevu commented
@markolovric same issue can still occur in screen sizes lower than 1263px, but at point question arises if we want to support such small screen sizes.

2020-12-16 15:36 UTC, markolovric commented
Correct! Depends on the minimum resolution we want to support. @underscope?

2020-12-17 07:54 UTC, underscope requested changes

2020-12-17 07:54 UTC, underscope commented on client/components/catalog/Card/Tags/index.vue
> +        color="blue-grey lighten-4 mb-1"
mb-1 on color 🤔?

2020-12-17 07:54 UTC, underscope commented on client/components/catalog/Card/index.vue
> -  height: 11.5rem;
You can probably remove now overflow as well 🤔 ?

2020-12-17 07:56 UTC, underscope commented
@markolovric @hrvojevu  > 1200

2020-12-18 07:27 UTC, merged