Api video content element
ExtensionEngine/tailor pull request #716
Opened 2021-01-14 17:20 UTC by ikovac

2021-01-15 11:09 UTC, MiroDojkic requested changes

2021-01-15 11:09 UTC, MiroDojkic commented on client/components/content-elements/tce-api-video/server/index.js
> +const { afterLoaded, afterSave, beforeSave } = require('tce-apivideo/dist/server/index.js');
Can we import the whole module (assuming it only exports hooks) and then destructure it inside of exported object?
I.e.
```suggestion
const server = require('tce-apivideo/dist/server');
```

2021-01-15 11:09 UTC, MiroDojkic commented on client/components/editor/ActivityContent/ContainerList.vue
> +            .emit('error', err.response.data);
Does the element lose access to error's status and headers if we process it here?
If that's the case, it might be a good idea to emit the whole error object and process it within the element, otherwise we're setting ourselves for a breaking change in the future.

2021-01-15 11:09 UTC, MiroDojkic commented on package.json
> +    "http-errors": "^1.8.0",
Why was this bump needed?

2021-01-15 11:09 UTC, MiroDojkic commented on .env.example
> +API_VIDEO_API_KEY=
Might be sufficient to document this in the element's `README` to prevent bloating this file. 🤔

2021-01-18 08:43 UTC, ikovac commented on client/components/editor/ActivityContent/ContainerList.vue
> +            .emit('error', err.response.data);
`err.response.data` contains status code, but headers will be lost. I will fix it 👍

2021-01-18 08:49 UTC, ikovac commented on .env.example
> +API_VIDEO_API_KEY=
It's already documented there. Here is just a mini note to inform users if they never heard of that content element. Should I delete notes from here?

2021-01-20 13:51 UTC, MiroDojkic requested changes

2021-01-20 13:51 UTC, MiroDojkic commented on config/server/tce.js
> +const extensionElements = require('../../extensions/content-elements');
This will throw if there's no `index.js` in `extensions/content-elements`.

2021-01-20 13:51 UTC, MiroDojkic commented on client/components/editor/ActivityContent/ContainerList.vue
> +        });
We could reduce repetition here by factoring out ```this.$radio.channel(`element:${getElementId(element)}`)```

2021-01-20 13:51 UTC, MiroDojkic commented on server/content-element/hooks.js
> +    return Promise.resolve(elementHookTypes)
🙇‍♂️

2021-01-20 13:51 UTC, MiroDojkic commented on config/server/tce.js
> +  }), {});
Please consider if any of the following changes make it a bit easier to read:
```suggestion
const tceConfig = Object.keys(process.env)
  .map(key => key.match(/^TCE_(.*)/))
  .filter(Boolean)
  .reduce((config, [prefixedKey, key]) => ({
    ...config,
    [camelCase(key)]: process.env[prefixedKey]
  }), {});
```

2021-01-20 13:51 UTC, MiroDojkic commented on .env.example
> +TCE_API_VIDEO_API_KEY=
As discussed, please remove tce specific secrets from `.env.example` and keep them in the tce's readme.

2021-01-20 15:28 UTC, ikovac commented on server/content-element/hooks.js
> +    return Promise.resolve(elementHookTypes)
😂

2021-01-21 16:05 UTC, MiroDojkic approved these changes

2021-01-22 13:09 UTC, underscope requested changes

2021-01-22 13:09 UTC, underscope commented on config/server/tce.js
> +'use strict';
server root might not be the most appropriate place (don't want to pollute it over time). Why not part of common config (create folder and rename config.js => index.js)

2021-01-22 13:09 UTC, underscope commented
🎖️

2021-01-24 14:22 UTC, merged