Truncate long schema names
ExtensionEngine/tailor pull request #721
Opened 2021-01-26 09:08 UTC by mcapeta

Yet another hacktoberfest PR 😂 

This PR truncates long schema name so they stack nicely with the cog and publishing info indicator.
Before:
![before](https://user-images.githubusercontent.com/21145871/105823983-1ecb5880-5fbe-11eb-8088-aa3218ce59a0.png)
After:
![after](https://user-images.githubusercontent.com/21145871/105824030-27bc2a00-5fbe-11eb-9c66-6dc4dd0fcd5f.png)

2021-01-26 09:10 UTC, zcuric commented
@mcapeta v-tooltip to display full name on hover? 🤔

2021-01-26 13:15 UTC, mcapeta commented
> @mcapeta v-tooltip to display full name on hover? 🤔

@zcuric
Thanks for pointing me to display entire schema name if it's being truncated 😉 
Nevertheless, I don't like how if looks with the tooltip version for a few reasons:
 - tooltip is redundant for short schema names (we should somehow detect there is no text overflow to disable that 🤹 )
 - not looking good in my opinion (restyling the tooltip is an option, of course)
![long tooltip](https://user-images.githubusercontent.com/21145871/105847190-90ff6580-5fdd-11eb-99b9-746acff49e7a.png)

What I suggest here is the following:
![expand-schema-name (1)](https://user-images.githubusercontent.com/21145871/105848821-d45ad380-5fdf-11eb-9546-b4790bbcb77c.gif)

Cons of the suggested solution:
 - limited to max three lines (feel free to argue if you don't think that's enough, cc @markolovric)
 - transition implementation doesn't feel smooth with the CSS transition only so I leveraged `<v-hover/>` component, too

2021-01-26 14:25 UTC, markolovric commented
I am totally for the first sample, tooltip on hover for text overflow

2021-01-27 15:47 UTC, mcapeta commented
> I am totally for the first sample, tooltip on hover for text overflow

Done! Please note that tooltip exists for all schema names, not for truncated ones only.

2021-01-28 08:11 UTC, markolovric commented
Don't like it. 
You can look at a sample on tags, we are only showing a tooltip for truncated text.

![image](https://user-images.githubusercontent.com/41724080/106108559-b65cb280-6148-11eb-889b-0c65e4eb340d.png)

2021-01-30 20:44 UTC, abasic requested changes

2021-01-30 20:44 UTC, abasic commented on client/components/catalog/Card/index.vue
> +    text-overflow: ellipsis;
Vuetify has a class for this called [text-truncate](https://vuetifyjs.com/en/styles/text-and-typography/#wrapping-and-overflow).

2021-01-30 20:44 UTC, abasic commented on client/components/catalog/Card/index.vue
> +    align-items: center;
There are also [classes for flex](https://vuetifyjs.com/en/styles/flex/).

2021-01-30 20:44 UTC, abasic commented on client/components/catalog/Card/index.vue
> +    flex-grow: 1;
Also a class for [flex-grow](https://vuetifyjs.com/en/styles/flex/#flex-grow-and-shrink).

2021-02-01 15:26 UTC, abasic approved these changes

2021-02-07 17:12 UTC, underscope commented on client/components/catalog/Card/index.vue
> +      const { clientWidth, scrollWidth } = this.$refs.schemaName;
@mcapeta 
Would it make sense to hook into https://vuetifyjs.com/en/features/breakpoints/#breakpoint-service 🤡

2021-02-12 02:20 UTC, merged

2021-02-12 02:33 UTC, underscope commented
@mcapeta When you get a chance, extract it into a separate component so it doesn't pollute Card as much 😉 
ty ❤️